premailer.gemspec
This removes a warning from ruby 2.2.
=> bump htmlentities to 4.3.3

lib/premailer/premailer.rb, test/test_links.rb
This PR add an option called : unescaped_ampersand that when set to `true` should fix [#174](https://github.com/premailer/premailer/issues/174) and all the other related issues.
Check [this](http://stackoverflow.com/questions/19441750/do-ampersands-still-need-to-be-encoded-in-urls-in-html5) and [this](http://www.w3.org/TR/html401/appendix/notes.html#h-B.2.2), because using just `&` is not valid HTML4 and might be invalid HTML5 as well. But browsers just doesn't unescape it properly.
=> add option to unescape ampersand

lib/premailer/adapter/nokogiri.rb, test/test_premailer.rb
When using the Nokogiri adapter, parsing an empty string or file raises an error because a guard that checks for a body is improperly implemented.  This pull request fixes the guard to check for an empty array returned from `doc.search('body')` instead of checking for a truthy value.
=> Fix Nokogiri adapter empty string handling.

lib/premailer/html_to_plain_text.rb, test/test_html_to_plain_text.rb
Use  blah blah  to ignore blocks of html in the text email. Fixes #239
=> Add ignore blocks for text generation

.travis.yml, Gemfile
This fixes the tests for Ruby 2.2. Travis CI lists as failing right now, which worried me as I was considering this library for a project.
=> Update Gemfile to include test-unit on MRI 2.2

lib/premailer/adapter/nokogiri.rb
I had encountered an issue where `background-image`'s were been converted to attributes with the `url('...')` property as well. So I was seeing:
```
background='url("http://cdn.ymaservices.com/email_transactional/background.jpg?v=0000002")'
```
It was not being stripped due to the URL being wrapped in `"` and not `'`. This change ensures either will work.
```
background='http://cdn.ymaservices.com/email_transactional/background.jpg?v=0000002'
```
=> Allows removal of url("...") in nokogiri RELATED_ATTRIBUTES

lib/premailer/premailer.rb, lib/premailer/version.rb
Premailer should be able to use local css files (file paths, not urls). If the path is absolute, it starts with a '/' which was being removed.
=> Support for local css file

lib/premailer/adapter/hpricot.rb, lib/premailer/adapter/nokogiri.rb, lib/premailer/premailer.rb
In my case it's really useful to not create the shorthands since I'm using premailer to create html with inline style and then pass it to Docraptor to generate XLS files and docraptor don't support shorthand codes
=> Adds option to avoid shorthand creation

lib/premailer/adapter/hpricot.rb, lib/premailer/adapter/nokogiri.rb, test/test_misc.rb
Fixes #173 and removes other matched inline styles as well, not just `-premailer-` ones.
=> Remove inline styles which are attributes

lib/premailer/adapter/hpricot.rb, lib/premailer/adapter/nokogiri.rb, test/test_premailer.rb
After PR https://github.com/premailer/premailer/pull/267 was merged, I realized that option css_to_attributes was not being checked.
=> Check option css_to_attributes

README.md
Update the README to note that fact that data-premailer="ignore" also applies to 'link' tags.
=> Update README for 'ignore' flag

lib/premailer/adapter/nokogiri.rb, lib/premailer/adapter/nokogumbo.rb
Style lists without an ending semicolon  sometimes break layouts in Outlook.com. This PR adds semicolons to the end of style lists in the Nokogiri and Nokogumbo adapters.
=> Add missing semicolon to end of style lists.

lib/premailer/html_to_plain_text.rb
The only difference between the two cases were for single and double quotes. E.g.
<a href="/foo">bar</a>
<a href='/foo'>bar</a>
=> Simplify link regex

lib/premailer/html_to_plain_text.rb, test/test_html_to_plain_text.rb
This PR address two cases when wrapping is not working really well.
```
Long text before the actual link and then <a href="http://www.long.link"/>LINK TEXT</a> and  then more text that does not wrap
```
currently doesn't wrap because [this](https://github.com/premailer/premailer/blob/master/lib/premailer/html_to_plain_text.rb#L104) overrides any wrapping that happened. So you just get:
```
Long text before the actual link and then LINK TEXT ( http://www.long.link ) and then more text that does not wrap
```
while what should happen is:
```
Long text before the actual link and then LINK TEXT
( http://www.long.link ) and then more text that does not wrap
```
In this case (consider line length of 10)
```
Long     line new line
```
Because the extra space goes over the line limit, wrapping …
=> Improving wrap when link or many spaces are on the breaking point

lib/premailer/adapter/nokogiri.rb, lib/premailer/premailer.rb, test/test_misc.rb
Some css has semicolon within brackets, e.g. the embedded image:
```
#logo {content: url(data:image/png;base64,LOTSOFSTUFF)};}
```
An improved split with regex solved that problem.
I also removed some code that block tests for ruby 2.2.2. The code looks unnecessary to me.
=> Fix for css with semicolon within brackets

test/files/import.css, test/files/noimport.css, test/files/styles.css
I’m the original creator of Premailer – I got a message today saying these copyright statements were problematic in packaging Premailer for Debian.
The CSS was always intended to be under the main project’s license.  These extra copyright notices can be removed to prevent any ambiguity. 
Cheers, Alex
=> Remove Dialect copyright notices from CSS files

Gemfile.lock, lib/premailer/premailer.rb
Ruby 1.9.1+ has the ability to guess the right input encoding to use via `String#encoding`.
=> Use input's own encoding if available

lib/premailer/premailer.rb, test/test_premailer.rb
My prior PR may cause breaking changes to users of this library, and I don't want to cause encoding-related problems for people. The documentation for `:input_encoding` is clear enough to indicate that it should regularly be set when using this library and 'ASCII-8BIT' is a sane default. This change reverts my PR yesterday and patches the test to set the correct input encoding to silence the Nokogiri warnings.
=> Revert encoding change

lib/premailer/adapter/hpricot.rb
Adds a deprecation notice whenever the Hpricot adapter is included.
Message preview:
```
[DEPRECATED] Premailer's Hpricot adapter will be removed with the next major release. Change your :adapter option to :nokogiri or remove the `hpricot` gem from your application to silence this warning. (Called from premailer/test/test_warnings.rb:91:in `new')
```
=> Add Hpricot deprecation notice

lib/premailer/html_to_plain_text.rb, test/test_html_to_plain_text.rb
When the text of the anchor is the same as the link (most often the case with email addresses), there is no need to repeat both.
```
<a href="mailto:mail@example.com">mail@example.com</a>
```
currently becomes 
```
mail@example.com ( mail@example.com )
```
Which is redundant. Now we could debate if the result should be with or without brackets. I prefer without  (and that's in this PR) because for the email it makes kind of sense. Brackets on the other hand do give it visibility. Still, brackets could result in strange cases when used in sentence. Eg:
```
Check it out at ( http://example.com )
```
instead a more simple
```
Check it out at http://example.com
```
=> Do not repeat text if the anchor content is the same as the link

lib/premailer/premailer.rb
I feel like if io_exceptions are enabled, it should probably raise file not found exceptions for local CSS files... it could probably do with a test.
Thoughts?
=> Raise file not found exceptions if local file isn't found

README.md
Hopefully this will help others avoid wasting time debugging the to_plain_text bug (https://github.com/premailer/premailer/issues/201).
=> update example to work around to_plain_text bug

lib/premailer/executor.rb
Typo in `executor.rb` means remove_scripts option wasn't working from the CLI
=> Fix `remove_scripts` option

.travis.yml, Gemfile.lock, lib/premailer/adapter.rb, lib/premailer/adapter/nokogiri_fast.rb, premailer.gemspec, test/test_adapter.rb
Premailer right now has three adapters namely hpricot, nokogiri and nokogumbo. As for the adapters themselves, they work fine, however, the performance of all the adapters are very slow in terms of running time.
We've earlier raised this issue - #317. We also tried the solution proposed by @akzhan on improving the performance, however, the slowness is not with the libraries used, however with the Algorithm that was being used to search the document. In some pathological cases, when the email DOM element is really large especially when we are using tables to support responsiveness across email clients. Because of this, it takes 400-500 seconds just to inline the styles. Even for smaller DOM cases, the time taken is more than 10 seconds which in computing terms, is years.
So we have tuned …
=> Adding Nokogiri Fast adapter and fix travis setup

lib/premailer/adapter/nokogiri_fast.rb
A minor change to the Nokogiri Fast adapter. I had earlier used the Nokogumbo's code instead of Nokogiri's. Can you please merge this change and bump the version ?
Thanks
=> Nokogiri Fast: Use HTML instead of HTML5

README.md
No need to do a release, just a readme update.
=> Update readme about premailer adapters

lib/premailer.rb, lib/premailer/adapter/nokogiri.rb, lib/premailer/adapter/rgb_to_hex.rb, lib/premailer/premailer.rb, test/test_premailer.rb
- Created to deal with rgb colors messing with our clients' email backgrounds
- Converts rgb colors to hex
- If color is not rgb it remains unchanged
- Includes tests
=> RGB to Hex Option

lib/premailer/adapter/nokogiri.rb
Updates to Gmail mobile apps mean that styles placed inside the <body> tag will be stripped. It is better supported all round to have style element within <head> tags and outside of the body. The following article outlines recent rendering changes:
https://www.campaignmonitor.com/blog/email-marketing/2016/10/gmail-update-googles-rendering-refresh/
=> Move styles to the head element

CHANGELOG.md, lib/premailer.rb, lib/premailer/version.rb
Hi there,
I use the premailer gem v1.10.1 via the premailer-rails gem v1.9.5 and I also use the addressable gem v2.3.8.
I found an error when I executed the `bundle exec rake db:create` command.
I saw the following logs.
```
bundle exec rake db:create --trace
rake aborted!
LoadError: cannot load such file -- addressable
/home/ubuntu/liquid-pay-platform/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
/home/ubuntu/liquid-pay-platform/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
/home/ubuntu/liquid-pay-platform/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency' …
```
=> Fix LoadError addressable with Addressable 2.3.8

lib/premailer/html_to_plain_text.rb, test/test_html_to_plain_text.rb
Look at issue https://github.com/premailer/premailer/issues/8 ( Premailer should preserve HTML entities ) 
Nokogiri converts in actual chars, please do not remove actual chars!
=> back whitespaces

lib/premailer/html_to_plain_text.rb, test/test_html_to_plain_text.rb
I suspect the the fact that the dot and the \s were overlapping for characters such as the space caused the regexp engine to try to match a long string of spaces with every permutation of both possibilities.
=> Fix exponential regexp in convert_to_text

lib/premailer/adapter/nokogiri.rb
The integration with Nokogiri for parsing HTML currently requires and enforces a full HTML document (including doctype, html, and body tags). If you provide premailer an HTML fragment, Nokogiri will wrap the content unnecessarily.
This is happening because the Nokogiri integration is only using the HTML parser, not the HTML Fragment parser that Nokogiri provides.
While I augmented premailer to resolve a problem that I have on a project, this pull request proposes a solution for the problem and I would like to see it integrated into the official repository.
=> Support for Nokogiri Fragment

lib/premailer/adapter/nokogiri.rb, lib/premailer/adapter/nokogiri_fast.rb
The bug was introduced in #350 and it's related to operator precedence. 
This caused the option `:input_encoding` to be ignored.
=> Fix input encoding in Nokogiri adapters

.travis.yml, lib/premailer/adapter/nokogumbo.rb, lib/premailer/premailer.rb, test/test_html_to_plain_text.rb, test/test_links.rb, test/test_misc.rb, test/test_premailer.rb, test/test_warnings.rb
This PR gets all the tests passing again and going green on travis-ci. It does this by fixing a number of interrelated issues:
* Change to the way the adapter is loaded into premailer so it's done on a per-instance basis rather than globally.
* Always set the adapter in the unit tests (rather than depending on the defaults) to stop the results of the tests being order dependent.
* The html_fragment option was doing exactly the opposite of what it was supposed to do for the nokogumbo adapter
* A small fix to one of the tests to make slightly more valid html so the html5 parser in nokogumbo wouldn't throw away the result
* Also, to ensure the build on travis-ci is the same as your local development copy this PR removes the line in .travis.yml which removes the Gemfile.lock file. Now, if you …
=> Get all unit tests passing again (by fixing a number of interrelated issues)

README.md
#365 Think others would find it useful to know about the -premailer-align attribute without reviewing the source.
=> Add -premailer-align CSS attribute to README

README.md, lib/premailer/html_to_plain_text.rb
This PR adds documentation for the annotations that can be added to HTML to omit sections in the plaintext output. We've been using this Gem for nearly 2 years, but only became aware we could do this once I looked at the source. Thanks for creating a great library 😄 .
=> Plaintext documentation

lib/premailer/adapter/nokogiri.rb, lib/premailer/adapter/nokogiri_fast.rb, lib/premailer/adapter/nokogumbo.rb, lib/premailer/premailer.rb, test/test_misc.rb
Added a config option to allow dropping unused CSS styles from the document. The default behavior is to include any unmerged (non-inlined) styles in a style block at the top of the body. However this can result in a huge block of unneeded css that can make your emails very long (causing them to get clipped in the client). This option lets you turn off that behavior.
I added a test that's passing for my change, but there were a lot of tests failing already which I didn't have time to look at.
=> add option to drop unused css styles

README.md
👋 
I thought it would be helpful to draw more attention to the configuration options in the readme.
The new `drop_unmergeable_css_rules` is very useful (we're now using it at GitHub and it has resulted in a nice size reduction for emails using premailer).
Thanks!
=> Add a section to highlight the configuration options for premailer

lib/premailer/html_to_plain_text.rb, test/test_html_to_plain_text.rb
This PR is a duplicate of #363, but seeing as that one is over a year old, I decided to clean it up a bit and resubmit.
The basic problem here is that with multiple `img` tags on the same line, if the first one doesn't have an `alt` attribute, but a later one does, the regular expression will greedily match everything in between and throw it away.
Under normal circumstances, the regular expression will convert each `img` tag to whatever it's alt text value is.
```ruby
Premailer.new('<img alt="before"> then <img alt="after">').to_plain_text
=> "before then after"
```
But here where the first one doesn't have any alt text, the entire string matches the regex for a single img tag and the word `'just'` is removed entirely from the output.
```ruby
Premailer.new('<img> just <img …
```
=> Ensure img alt text handled properly

lib/premailer/adapter/nokogiri.rb, lib/premailer/adapter/nokogiri_fast.rb, lib/premailer/adapter/nokogumbo.rb
Prior to this commit the test suite was outputting warnings about
calling Kernel#open. With this commit the test suite is back to a clear
output with nothing but green dots.
```
premailer/adapter/nokogiri_fast.rb:209: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
premailer/adapter/nokogumbo.rb:207: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
premailer/adapter/nokogiri.rb:207: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
```
=> Fix URI.open deprecation warnings

lib/premailer/premailer.rb, test/helper.rb
`File.exists?` is deprecated in Ruby 2.8
```
irb(main):001:0> RUBY_VERSION
=> "2.7.1"
irb(main):002:0> File.exists?("")
=> false
irb(main):003:0> File.exist?("")
=> false
```
```
irb(main):001:0> RUBY_VERSION
=> "2.8.0"
irb(main):002:0> File.exists?("")
(irb):2: warning: File.exists? is deprecated; use File.exist? instead
=> false
irb(main):003:0> File.exist?("")
=> false
```
=> Replace deprecated File.exists? with File.exist?

lib/premailer/adapter/nokogiri.rb, lib/premailer/adapter/nokogiri_fast.rb, lib/premailer/adapter/nokogumbo.rb
MS Outlook doesn't honor `<img width="200px">` and instead requires `<img width="200">`. The Mozilla docs also state "Must be an integer without a unit."
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-width
This change converts `-premailer-width: 100px` to `width=100` in the HTML attribute (same for `height`). It is useful when working with SASS variables for example so that you can do:
```
$my-width: 100px;
width: $my-width;
-premailer-width: $my-width;
```
I've made this change specific to the width/height attrs only. I can't think of any case where you wouldn't want to apply this transformation.
=> Remove "px" from HTML width/height attribute

CHANGELOG.md, lib/premailer/adapter/nokogiri.rb, lib/premailer/adapter/nokogiri_fast.rb, lib/premailer/adapter/nokogumbo.rb, lib/premailer/version.rb
This is a fix to the recently merged PR. My apologies for the oversight. I've tested this and it's now working as intended.
Version/changelog also added.
=> Fix to converting inline html 100px to 100

lib/premailer/adapter/nokogiri.rb, lib/premailer/adapter/nokogiri_fast.rb, lib/premailer/adapter/nokogumbo.rb
Now requires beginning and ending quote style to match, and matches lazily so two url()s on the same line are treated independently.
=> Make 'url()' wrapper stripping more robust

lib/premailer/premailer.rb
TLDR: Since Addressable::URI is now used instead of URI, uri are now normalized better than before, this loop is unneeded
Hello,
We discovered this with an issue with an earlier version, where this loop would go infinite in links like https://github.com/../../file.css
Because "../../" would match the regex, be replaced by itself and go on again and again.
e.g.
```ruby
require 'addressable'
uri = "https://github.com/one/../../file.html"
URI.parse(uri).normalize.to_s
Addressable::URI.parse(uri).normalize.to_s
```
Currently the while block is doing nothing because Addressable URI already does the job so might as well remove it.
=> Minor: Remove relative cleaner loop in canonicalize

premailer.gemspec
Tools like VersionEye are using this information for license compliance analysis.
=> Adding license information to the gemspec

lib/premailer/html_to_plain_text.rb, test/test_html_to_plain_text.rb
This addresses https://github.com/premailer/premailer/issues/404.
Simply making the `href` portion of the original regex optional didn't work for globbing reasons.
=> Find `a` tags first and then parse them for `href`s

.github/workflows/actions.yml, Gemfile.lock, lib/premailer/adapter/nokogumbo.rb, premailer.gemspec
This fixes a number of CVEs and drops the need for nokogumbo: https://github.com/sparklemotion/nokogiri/issues/2205
Also drops Ruby 2.5 and 2.6 since they reached EOL (https://www.ruby-lang.org/en/downloads/branches/).
=> Update nokogiri to v1.13.4

lib/premailer.rb, lib/premailer/adapter/nokogiri.rb, lib/premailer/adapter/nokogiri_fast.rb, lib/premailer/adapter/nokogumbo.rb
FIPS-compliant systems can no longer use MD5 as it is
cryptographically broken. This commit switches the hash algorithm to
SHA256.
=> Switch MD5 hash to SHA-256

lib/premailer/adapter/nokogiri.rb, test/test_premailer.rb
Use new rule_set_exceptions in nokogiri adapter to swallow invalid css errors silently.
This will fix #420.
=> Use rule_set_exceptions option in nokogiri

.github/workflows/actions.yml, Gemfile.lock
Ruby 3.2 has [been released](https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/)! Let's add it to the build matrix.
Also run `bundle update` to get the latest dependencies.
=> CI: add Ruby 3.2 to the test matrix

lib/premailer/adapter/nokogiri.rb, lib/premailer/adapter/nokogiri_fast.rb, lib/premailer/adapter/nokogumbo.rb
The minimum supported version of Ruby is now 2.7, so this conditional behaviour is no-longer needed.
=> Remove conditional behaviour for Ruby 1.9

lib/premailer/premailer.rb
This avoids `Psych::BadAlias: Unknown alias` errors when running on Ruby 2.7, but with Psych version 4 included in the Gemfile.
=> Conditionally set YAML loading arguments based on psych gem version

lib/premailer/adapter/nokogiri.rb, test/test_premailer.rb
Have been suffering from some errors generating within `RuleSets.expand_shorthand!` with invalid CSS such as `margin: 0px 0px 0px 0 px`. 
I guess these errors should also be handled by the `rule_set_exceptions` config?
Similar to a comment left on an issue before, but I don't think any work was done on it: https://github.com/premailer/premailer/issues/420#issuecomment-1273523818
Example error:
```
ArgumentError: Cannot parse 0px 0px 0px 0 px
/home/david.weir/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/css_parser-1.14.0/lib/css_parser/rule_set.rb:378:in `block in expand_dimensions_shorthand!'
/home/david.weir/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/css_parser-1.14.0/lib/css_parser/rule_set.rb:353:in `each'
/home/david.weir/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/css_parser- …
```
=> catch errors during expand_shorthand and handle using rule_set_exceptions

lib/premailer/adapter/nokogiri.rb, test/test_premailer.rb
Currently just a failing test for a form of CSS that is raising an argument error even with `rule_set_exceptions` set to false
=> Failing test case where Adapter::Nokogiri#to_inline_css raises ArgumentError when rule_set_exceptions: false

premailer.gemspec
Make the gem more secure by requiring that all privileged operations by any of the owners require OTP.
Ref: https://guides.rubygems.org/mfa-requirement-opt-in/
=> Opt-in for MFA requirement

test/files/chars.html, test/test_premailer.rb
This commit fixes test behavior, but unfortunately does not address the new issues with Nokogiri 1.16, which should be properly investigated (again)
Nokogiri 1.16 (I think through the underlying libxml) is replacing the html entities with escaped ascii chars, maybe to provide smaller files, couldn't tell
=> Fix tests encoding

.github/workflows/actions.yml, CHANGELOG.md, premailer.gemspec
Ruby 2.7 reached EOL in March '23. This commit will allow to bump up the minimum required Nokogiri version to 1.16
Ref: #443
Thank you for your contribution!
=> Drop Ruby 2.7 compatibility

CHANGELOG.md, Gemfile.lock, premailer.gemspec, test/test_premailer.rb
There have been two recent changes in libxml2 2.11 and than 2.12 which broke two specs related to the conversion of UTF-8 chars.
This commit sets the minimum required Nokogiri version to 1.16 which bundles libxml2 2.12, in order to have a predictable behaviour.
References:
- #430
- sparklemotion/nokogiri#2965
- sparklemotion/nokogiri#3032
- GNOME/libxml2@f1c1f5c
- GNOME/libxml2@37cedc0
Close #443
Thank you for your contribution!
=> Require Nokogiri >= 1.16

CHANGELOG.md, lib/premailer/adapter/rgb_to_hex.rb, test/test_premailer.rb
This commit adds support for converting rgb with alpha modifiers (e.g. `rgb(1 2 3 / 0.5)`) to hex, which are featured prominently in Tailwind (to the point that even turning them off doesn't seem to fully turn them off)
More info on these:
https://css-tricks.com/no-comma-color-functions-in-css/
=> Add support for no-comma RGB functions

README.md
I love the ability to omit HTML content when generating the plain text version. I only realized it was possible after searching and stumbling across https://github.com/premailer/premailer/pull/244.
Seeing that it was not documented in the README, this PR adds a section about generating plain text versions and how to omit HTML content from it.
=> README: Add section on generating plain text versions

CHANGELOG.md, lib/premailer/adapter/nokogiri.rb, lib/premailer/html_to_plain_text.rb, lib/premailer/premailer.rb
There was a deprecation warning for chilled strings merged recently in Ruby: https://github.com/ruby/ruby/commit/12be40ae6be78ac41e8e3f3c313cc6f63e7fa6c4
And with that we started to see the following warning coming from `premailer`:
```
vendor/gems/3.4.0/ruby/3.4.0+0/gems/premailer-1.13.1/lib/premailer/premailer.rb:269: warning: literal string will be frozen in the future
```
These changes remove those errors by unfreezing strings when they should be mutable. They get the test suite to pass with RUBYOPT="--enable-frozen-string-literal", which will be the default in the future.
=> Prepares for all strings to be frozen
